# Server
server.port=8080
spring.application.name=plataforma-cursos

# H2 Database (simple, no requiere motor externo)
spring.datasource.url=jdbc:h2:file:./data/guiasdb;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# AWS S3
aws.s3.bucket=${AWS_S3_BUCKET:guias-despacho-bucket}
aws.region=${AWS_REGION:us-east-1}

# EFS - Directorio de almacenamiento temporal
app.efs.path=${EFS_MOUNT_PATH:/app/efs}

# Logging
logging.level.com.duocuc=DEBUG

# ===== Spring Security / OAuth2 Resource Server — Semana 8 =====
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AZURE_AD_B2C_JWKS_URI:https://duocazurecloud.b2clogin.com/duocazurecloud.onmicrosoft.com/b2c_1_duocdemoazure_registro_login/discovery/v2.0/keys}
app.security.expected-issuer=${AZURE_AD_B2C_ISSUER_URI:https://duocazurecloud.b2clogin.com/f80f2065-e1f4-405a-a669-83e93e4e28d7/v2.0/}

# ===== RabbitMQ — Semana 8 =====
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASS:guest}

# ===== Actuator =====
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
